### ISSUE TITLE
index out of range 

### ISSUE THREAD

**Issue by anuku7** [francescocarlucci/wphashcrash#1]
hi can you fix it ?
2020/09/19 08:40:52 Executed in 0.000000
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
main.main()
	/Users/m/go/src/github.com/francescocarlucci/wphashcrash/main.go:32

**Comment by francescocarlucci** [comment]
It happens if you forget to pass the 2nd argument to the script.

`wphashcrash 'hash' path/to/dictionary.txt`
