### ISSUE TITLE
go get pull error. 

### ISSUE THREAD

**Issue by Kchristian-Untangle** [francescocarlucci/wphashcrash#2]
Receiving the following output from go when attempting to pull. Line 30:

root@testhost:~# go get github.com/francescocarlucci/wphashcrash
 \# github.com/francescocarlucci/wphashcrash
go/src/github.com/francescocarlucci/wphashcrash/main.go:30:17: error: shift count not unsigned integer
   hashloop := 1 << strings.Index(itoa64, string(hash[3]));

**Comment by francescocarlucci** [comment]
Which version of golang are you running?
